spring.application.name=food_delivery_app

#spring.security.user.name=admin
#spring.security.user.password=admin

spring.datasource.url=jdbc:postgresql://localhost:5432/food-delivery-app
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#jwt.secret=bXlTZWNyZXRLZXlteVNlY3JldEtleW15U2VjcmV0S2V5MTIz
#jwt.expiration=3600000

